/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ShopRouteRouteImport } from './routes/_shop/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedBooksRouteImport } from './routes/_authenticated/books'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as ShopAccountRouteImport } from './routes/_shop/account'
import { Route as ShopCartRouteImport } from './routes/_shop/cart'
import { Route as ShopCheckoutRouteImport } from './routes/_shop/checkout'
import { Route as ShopOrdersRouteImport } from './routes/_shop/orders'
import { Route as ShopShopRouteImport } from './routes/_shop/shop'
import { Route as ShopShopBookIdRouteImport } from './routes/_shop/shop.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksRoute = AuthenticatedBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopShopRoute = ShopShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopShopBookIdRoute = ShopShopBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => ShopShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/books': typeof AuthenticatedBooksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pos': typeof AuthenticatedPosRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/orders': typeof ShopOrdersRoute
  '/shop': typeof ShopShopRouteWithChildren
  '/shop/$bookId': typeof ShopShopBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/books': typeof AuthenticatedBooksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pos': typeof AuthenticatedPosRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/orders': typeof ShopOrdersRoute
  '/shop': typeof ShopShopRouteWithChildren
  '/shop/$bookId': typeof ShopShopBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_shop': typeof ShopRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/books': typeof AuthenticatedBooksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_shop/account': typeof ShopAccountRoute
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/orders': typeof ShopOrdersRoute
  '/_shop/shop': typeof ShopShopRouteWithChildren
  '/_shop/shop/$bookId': typeof ShopShopBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activity'
    | '/books'
    | '/dashboard'
    | '/pos'
    | '/sales'
    | '/team'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/shop'
    | '/shop/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activity'
    | '/books'
    | '/dashboard'
    | '/pos'
    | '/sales'
    | '/team'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/shop'
    | '/shop/$bookId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_shop'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/books'
    | '/_authenticated/dashboard'
    | '/_authenticated/pos'
    | '/_authenticated/sales'
    | '/_authenticated/team'
    | '/_shop/account'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/orders'
    | '/_shop/shop'
    | '/_shop/shop/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books': {
      id: '/_authenticated/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_shop/account': {
      id: '/_shop/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/orders': {
      id: '/_shop/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/shop': {
      id: '/_shop/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopShopRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_shop/shop/$bookId': {
      id: '/_shop/shop/$bookId'
      path: '/$bookId'
      fullPath: '/shop/$bookId'
      preLoaderRoute: typeof ShopShopBookIdRouteImport
      parentRoute: typeof ShopShopRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedBooksRoute: typeof AuthenticatedBooksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedBooksRoute: AuthenticatedBooksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ShopShopRouteChildren {
  ShopShopBookIdRoute: typeof ShopShopBookIdRoute
}

const ShopShopRouteChildren: ShopShopRouteChildren = {
  ShopShopBookIdRoute: ShopShopBookIdRoute,
}

const ShopShopRouteWithChildren = ShopShopRoute._addFileChildren(
  ShopShopRouteChildren,
)

interface ShopRouteRouteChildren {
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopShopRoute: typeof ShopShopRouteWithChildren
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopShopRoute: ShopShopRouteWithChildren,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ShopRouteRoute: ShopRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
